# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout MagicMirror repo
      uses: actions/checkout@v2
      with:
        repository: MichMich/MagicMirror
        path: MagicMirror
    
    - name: Checkout Module repo
      uses: actions/checkout@v2
      with:
        path: MagicMirror/modules/mmm-testing
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        cd MagicMirror
        Xvfb :99 -screen 0 1024x768x16 &
        export DISPLAY=:99
        npm install
    - run: |
        cd MagicMirror/modules/mmm-testing
        npm install
        npm ci
        npm run build --if-present
        npm run test:js
